spring:
  cloud:
    gateway:
      default-filters:
      - TokenRelay=
      - RemoveRequestHeader=Cookie, Set-Cookie
      routes:
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/api/v1/license/**
        filters:
        - RewritePath=/api/(?<path>.*), /$\{path}
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/api/v1/organization/**
        filters:
        - RewritePath=/api/(?<path>.*), /$\{path}
      - id: config-service
        uri: lb://config-service
        predicates:
        - Path=/api/v1/config/**
        filters:
        - RewritePath=/api/v1/config/(?<path>.*), /$\{path}
      - id: eureka-service
        uri: lb://eureka-service
        predicates:
        - Path=/dashboard/eureka/**
        filters:
        - RewritePath=/dashboard/eureka/(?<path>.*), /$\{path}
        - RequestHeaderSize=40KB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      endpoint:
    gateway:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
logging:
  level:
    com.optimagrowth: DEBUG
security:
  cors:
    allowedOrigins: http://localhost:4200 # TODO: Only for development. Override this for higher environments
    allowedMethods: '*'
    allowedHeaders: '*'