spring:
  cloud:
    gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      endpoint:
    gateway:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
